### ISSUE TITLE
Adding url to performer in events

### ISSUE THREAD

**Issue by WeaverStever** [teran/mediawiki-GoogleRichCards#6]
Hi,
I am trying to add a url in Events for Performer. Looked pretty straight forward, but new to php.

~~~
        if($e->{'performer'}) {
          $event['performer'] = array(
            '@type'   => 'PerformingGroup',
            'url'     => $this->getRawURL($e->{'performerurl'}),
            'name'    => $this->getMetadataField($e, 'performer', 'performer'),            
          );
~~~ 

The output I'm getting on SDTT is 
~~~
"Performer":{"@type":"PerformingGroup","name":"Aubrey Logan","url":null}
~~~

I'm not seeing any fixed indexes for the arrays, do I need to recompile the php somehow?

**Comment by WeaverStever** [comment]
Duh, my bad, forgot to add to the events template.

Thanks for the great extension!

**Comment by teran** [comment]
@WeaverStever no worries, thank you for using it :)
